version: '3.7'
services:
  db:
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  rails-invoice-processor:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - .:/app # add our local code to dockerfile
    depends_on:
      - db  # add all dependant container

volumes:
  postgres: # named volume